# Generated by Django 4.2.8 on 2023-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsession',
            name='meeting_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='meeting_schedule',
            field=models.DateField(null=True),
        ),
    ]
