# Generated by Django 4.2.8 on 2024-04-17 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_time', models.DateTimeField(default=None, null=True)),
                ('meeting_link', models.CharField(default=None, max_length=255, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='time',
        ),
        migrations.DeleteModel(
            name='MeetingDetails',
        ),
    ]
