# Generated by Django 4.2.8 on 2024-01-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_meeting_schedule_mentorsession_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellouser',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.yellouserprofile'),
        ),
    ]
