# Generated by Django 4.2.8 on 2024-01-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mentorsession_meeting_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsession',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('scheduled', 'scheduled')], default='pending', max_length=255),
        ),
    ]
