# Generated by Django 4.2.8 on 2024-02-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_yellouser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp_offer', models.CharField(max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mentorsession')),
            ],
        ),
    ]
