# Generated by Django 4.2.8 on 2024-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_alter_mentorsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails'),
        ),
    ]
