# Generated by Django 4.2.8 on 2024-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meetingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellouserprofile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
