# Generated by Django 4.2.8 on 2024-03-12 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_meetingdetail_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdetail',
            name='meeting_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
