# Generated by Django 4.2.8 on 2024-01-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mentorsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsession',
            name='meeting_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
